# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(795, 713)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_load = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load.setGeometry(QtCore.QRect(20, 10, 111, 23))
        self.btn_load.setObjectName("btn_load")
        self.btn_calculate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calculate.setGeometry(QtCore.QRect(20, 652, 751, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btn_calculate.setFont(font)
        self.btn_calculate.setObjectName("btn_calculate")
        self.label_path = QtWidgets.QLabel(self.centralwidget)
        self.label_path.setGeometry(QtCore.QRect(430, 10, 341, 21))
        self.label_path.setObjectName("label_path")
        self.log_text = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.log_text.setGeometry(QtCore.QRect(20, 130, 761, 501))
        self.log_text.setObjectName("log_text")
        self.working_time = QtWidgets.QLineEdit(self.centralwidget)
        self.working_time.setGeometry(QtCore.QRect(220, 47, 113, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.working_time.sizePolicy().hasHeightForWidth())
        self.working_time.setSizePolicy(sizePolicy)
        self.working_time.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.working_time.setFont(font)
        self.working_time.setObjectName("working_time")
        self.label_working_time = QtWidgets.QLabel(self.centralwidget)
        self.label_working_time.setGeometry(QtCore.QRect(30, 50, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_working_time.setFont(font)
        self.label_working_time.setObjectName("label_working_time")
        self.label_accuracy = QtWidgets.QLabel(self.centralwidget)
        self.label_accuracy.setGeometry(QtCore.QRect(30, 90, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_accuracy.setFont(font)
        self.label_accuracy.setObjectName("label_accuracy")
        self.accuracy = QtWidgets.QLineEdit(self.centralwidget)
        self.accuracy.setGeometry(QtCore.QRect(373, 87, 113, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.accuracy.setFont(font)
        self.accuracy.setObjectName("accuracy")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Рассчёт маршрутов"))
        self.btn_load.setText(_translate("MainWindow", "Загрузить файл"))
        self.btn_calculate.setText(_translate("MainWindow", "Рассчитать"))
        self.label_path.setText(_translate("MainWindow", "Файл не выбран"))
        self.working_time.setText(_translate("MainWindow", "720"))
        self.label_working_time.setText(_translate("MainWindow", "Рабочее время (мин)"))
        self.label_accuracy.setText(_translate("MainWindow", "Точность рассчёта расстояния (10-50)"))
        self.accuracy.setText(_translate("MainWindow", "20"))
